FROM golang:1.25 AS build

WORKDIR /app

# Копируем файлы модулей
COPY go.mod go.sum ./

# Скачиваем зависимости
RUN go mod download

# Копируем исходный код бэкенда
COPY . ./

# Собираем приложение
ENV CGO_ENABLED=0
RUN go build -o /app/bin/app ./cmd/main.go

FROM alpine:3.20

COPY --from=build /app/bin/app /app

ENTRYPOINT [ "/app" ]